library(shiny)
library(shiny.fluent)
library(imola)
library(stringr)
library(dplyr)
library(readr)
library(leaflet)
library(glue)
library(purrr)
library(sf)
library(readxl)
library(shinyWidgets)
library(stringi)
library(stringdist)

# Read data
lineas <- read_sf("./data/lineas/lineas.shp")
estaciones <- read_excel("./data/estaciones.xlsx")
